# Generated by Django 5.2.13 on 2026-04-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Petrol', 'Petrol'), ('Food', 'Food'), ('Travel', 'Travel'), ('Snacks', 'Snacks'), ('Misc', 'Misc')], max_length=20)),
                ('credited_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('credit_remark', models.CharField(blank=True, default='', max_length=300)),
                ('debited_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('debit_remark', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.branch')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
