# Generated by Django 5.2.13 on 2026-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['location'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
