# Generated by Django 5.2.13 on 2026-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_branch_options_remove_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='credit_payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='credit_person',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='debit_payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='debit_person',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
