# Generated by Django 5.2.13 on 2026-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_credit_payment_mode_expense_credit_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], max_length=30, unique=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['payment_mode'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Food', 'Food'), ('Travel', 'Travel'), ('Snacks', 'Snacks'), ('Stationary', 'Stationary'), ('Toolkit', 'Toolkit'), ('Misc', 'Misc')], max_length=20),
        ),
    ]
