# Generated by Django 5.2.13 on 2026-04-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_billingreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingreminder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_reminders', to='expenses.branch'),
        ),
    ]
