# Generated by Django 5.2.14 on 2026-06-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_billingreminder_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=300)),
                ('person', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_debits', to='expenses.branch')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
